### ISSUE TITLE
你好，请教一个问题。

### ISSUE THREAD

**Issue by EdisonChenZX** [ucloud/ufile-sdk-java#20]
UfileClient.object(OBJECT_AUTHORIZER, config)
         .putObject(file, "text/plain")
         .nameAs("save as keyName")
         .toBucket("upload to which bucket")
请问这里的nameas跟tobucket是要填写什么呢

**Comment by JoshuaYin** [comment]
nameAs: 上传后在云端的文件名
toBucket: 要上传到的云端仓库名称

**Comment by JoshuaYin** [comment]
> UfileClient.object(OBJECT_AUTHORIZER, config)
> .putObject(file, "text/plain")
> .nameAs("save as keyName")
> .toBucket("upload to which bucket")
> 请问这里的nameas跟tobucket是要填写什么呢

nameAs: 上传后在云端的文件名
toBucket: 要上传到的云端仓库名称

**Comment by Crotion** [comment]
nameAs含有/时在进行删除对象操作时会转译为%2F,请问如何解决？谢谢！
nameAs : image/612b8ffc86f250c83753aadb4588e4ff8149e9c320ee8944e1e66d8c.png
