### ISSUE TITLE
文件上传时报错

### ISSUE THREAD

**Issue by rdej2345** [ucloud/ufile-sdk-java#31]
文件上传时报错，使用的控制台生成的令牌，使用管理工具可以上传，报错如下：
cn.ucloud.ufile.exception.UfileServerException: {"ResponseCode":403,"RetCode":-148658,"ErrMsg":"invalid signature","X-SessionId":"48b70da8-12d9-4609-88cf-3548193810df"}

**Comment by JoshuaYin** [comment]
接入异常请寻求ucloud技术支持反馈
