### ISSUE TITLE
关于创建外链时的几个问题

### ISSUE THREAD

**Issue by ymind** [ucloud/ufile-sdk-java#35]
1. 是否能够支持自定义`Content-Disposition`等响应头？
2. 是否能够允许在创建外链时另外指定host，而不是使用`ObjectConfig.host()`？
3. 自定义域名时如何使用https？

**Comment by delexxie** [comment]
1、Response.AppendHeader("Content-Disposition","attachment;filename=FileName.txt");
我们是支持的，支持方法是 在下载 url 加个参数： ufileattname=XXX 就可以指定
例子：  http://a.cn-bj.ufileos.com/a/b/key001?ufileattname=文件1.txt

2、如果是下载，可以指定外网host 名，需要在ucloud 控制台 ufile bucket 管理里注册一下自定义域名； 然后就可以替代 ufile 的默认域名去使用；

3、自定义域名目前暂不支持https

**Comment by ymind** [comment]
* 问题3：明白。
* 问题2：仍有疑问。假设我绑定了n个不同的域名，我希望根据情况为不同的文件指定不同的下载域名，如何实现？按照当前的SDK貌似只能从头构建`UfileClient`方可实现，也可以满足需要，只是不够便利。
* 问题1：有些小疑问：
  - 在文档中心未能找到`ufileattname`这个参数，SDK中也貌似没有提供相关方法。通过将该参数追加至url末尾测试通过，希望sdk能够内置支持；
  - `Content-Disposition` 有 `inline` 和 `attachment` 两种模式，如果我希望使用 `inline` 模式如何实现？这个也是有用处的，比如在浏览器打开或者网页显示的时候与平常一样，但若我将文件“另存为”到设备的时候，我希望自定义的文件名能够用上并作为默认的文件名保存。如果统一使用 `attachment` 模式处理，我曾经遇到过img标签中的图片被直接弹窗下载的现象（比较久远的事情了，虽然很久没遇到了，但仍然很忌惮），我现在的做法是统一使用 `attachment` 模式。

**Comment by JoshuaYin** [comment]
问题1：inline为ufile文件下载默认模式。对于attachment模式，sdk会在GenerateObjectPublicUrlApi和GenerateObjectPrivateUrlApi两个构造下载链接的API中，提供配置方案，并在后续版本中发布。
问题2：不同域名可以创建不同的 bucket 去对应
