### ISSUE TITLE
ObjectApiBuilder.getDownloadUrlFromPrivateBucket中 expiresDuration没有效果

### ISSUE THREAD

**Issue by DuoLaAMengDianHuanXiang** [ucloud/ufile-sdk-java#39]
我设置的值是10 ，但是一个小时过去了。这段代码生成的url，还是能访问到文件
`            String url = UfileClient.object(Constants.OBJECT_AUTHORIZER, config)
                    .getDownloadUrlFromPrivateBucket(keyName, bucketName, expiresDuration)
                    .createUrl();
`

**Comment by JoshuaYin** [comment]
这个要看你的bucket是public的还是private的
