### ISSUE TITLE
大写的文件后缀解析不出来

### ISSUE THREAD

**Issue by DuoLaAMengDianHuanXiang** [ucloud/ufile-sdk-java#53]
例如文件: file.pdf.PDF
一样能正常打开

但是MimeTypeUtil.getMimeType(keyName);会解析不出来
`
    public static String getMimeType(String fileName) {
        JLog.T(TAG, "[file name]:" + fileName);
        if (fileName == null || fileName == "" || !fileName.contains("."))
            return MIME_TYPE_MAP.get("");

        int lastDot = fileName.lastIndexOf(".");
        if (lastDot > (fileName.length() - 2))
            fileName = "";
        else
            fileName = fileName.substring(lastDot + 1);

        JLog.T(TAG, "[suffix]:" + fileName);
        // 转成小写去MIME_TYPE_MAP匹配
        String res = MIME_TYPE_MAP.get(fileName.toLowerCase(Locale.ROOT));

        return res == null || res.isEmpty() ? MIME_TYPE_MAP.get("") : res;
    }
`

**Comment by JoshuaYin** [comment]
MimeTypeUtil只是简便的兼容方法类，暂时无法自适应所有的文件后缀和比较特殊的大写后缀场景。
